### ISSUE TITLE
About pseudo labels generation

### ISSUE THREAD

**Issue by hxiaoj** [SooLab/Part2Object#2]
When I try to generate pseudo labels according to your code, I find some problems.

First, in line 158 of Part2Object/pseudo_mask_gen/project_feature.py is 'scene = torch.load(os.path.join(SCANNET_DATA, "train", scene_id)+".pth")["coord"]'.
However, the output of Part2Object/pseudo_mask_gen/vccs/data_prepare_ScanNet.py is files endwith 'ply', and the process rotate the origin coordinates, so I don't sure whether modify the path to the output of data_prepare_ScanNet.py in project_feature.py or using the origin coordinate as input in project_feature.py.

Second,  I find that the pesudo label generation part missing the code about generating the pseudo 2d masks using cutler.

Finally, the 164 line of Part2Object/pseudo_mask_gen/project_feature.py, 'frame_list = list(map(lambda x: x.split(".")[0], sorted(os.listdir("results8_2d/{}".format(scene_id)))))', if this means the path to scannet_frames_25k?

**Comment by zyjhxd** [comment]
我也是像根据代码生成伪标签，但显示没有lib.helper_ply

**Comment by hatimwen** [comment]
> 我也是像根据代码生成伪标签，但显示没有lib.helper_ply

Hi @zyjhxd ,
here: https://github.com/vLAR-group/GrowSP/blob/main/lib/helper_ply.py

**Comment by zyjhxd** [comment]
我想通过代码生成伪标签，但始终显示没有pclpy库，也始终安装不了这个包是为什么？

**Comment by hatimwen** [comment]
> 我想通过代码生成伪标签，但始终显示没有pclpy库，也始终安装不了这个包是为什么？

@zyjhxd 可以试试降低Python版本，比如 Python 3.8.19，然后 `conda install -c conda-forge -c davidcaron pclpy`

建议另外建一个Python 3.8.19环境跑`pseudo_mask_gen/vccs/initialSP_prepare_ScanNet.py`，其他代码有需要Python>=3.9

**Comment by zyjhxd** [comment]
请问代码中的data/frames_square在哪呢，而且dinov2/hubconf.py此文件也为出现，是不是缺少文件？

**Comment by hatimwen** [comment]
> 请问代码中的data/frames_square在哪呢，而且dinov2/hubconf.py此文件也为出现，是不是缺少文件？

@zyjhxd ,

前者我也不确定，等作者@YangBin55 回复吧； 

后者dinov2部分，你git clone 一下 dinov2的 repo (https://github.com/facebookresearch/dinov2) 安装一下就好了

**Comment by zyjhxd** [comment]
谢谢你，我在运行python project_feature.py出现错误File "project_feature.py", line 150, in <module>
    scene_list = sorted(os.listdir("data/frames_square/"))
FileNotFoundError: [Errno 2] No such file or directory: 'data/frames_square/'这是为什么呢？

**Comment by hatimwen** [comment]
> 谢谢你，我在运行python project_feature.py出现错误File "project_feature.py", line 150, in scene_list = sorted(os.listdir("data/frames_square/")) FileNotFoundError: [Errno 2] No such file or directory: 'data/frames_square/'这是为什么呢？

等作者回复说明一下这个是什么文件吧

**Comment by YangBin55** [comment]
Hi, data/frames_square is the image in the video stream of each scene obtained from the post-processing of the scannet dataset. But it is only used to get the list of all scene names in the code, you can refer to the official scannet code to get the frames_square file or modify it to other methods to get the corresponding scene names.

**Comment by zyjhxd** [comment]
是不是有无这个图像对实例分割没有影响呢？

**Comment by zyjhxd** [comment]
而且scannet代码中并没有用到frames_square这个文件

**Comment by zyjhxd** [comment]
> > 谢谢你，我在运行python project_feature.py时出现错误File "project_feature.py", line 150, in scene_list =sorted(os.listdir("data/frames_square/")) FileNotFoundError: [Errno 2] No such file or directory : 'data/frames_square/'这是为什么呢？
> 
> 等作者回复说明一下这个是什么文件吧

Hello, have you solved it yet?
