### ISSUE TITLE
Incorrect Links for Pseudo-Labels and Part2Object_df0.ckpt Checkpoint

### ISSUE THREAD

**Issue by hatimwen** [SooLab/Part2Object#3]
Hi, thank you for sharing this remarkable work and providing detailed instructions in the README!

I noticed that the link provided for the generated pseudo-labels in the README points to the checkpoint `Part2Object_df20.ckpt` instead:
https://github.com/SooLab/Part2Object/blob/620d27388e2602ff2de6e8ed544e9b040f32dd7c/README.md?plain=1#L82

Additionally, the links for the checkpoints corresponding to `Training-free Setting` and `0% data (Part2Object_df0.ckpt)` also incorrectly directs to `Part2Object_df20.ckpt`:
https://github.com/SooLab/Part2Object/blob/620d27388e2602ff2de6e8ed544e9b040f32dd7c/README.md?plain=1#L99-L109

Could you please update the links to point to the correct files? Thanks again for your hard work and support!

**Comment by YangBin55** [comment]
Sorry for using the wrong link, we've updated and fixed it, thanks for pointing out our mistake!

**Comment by hatimwen** [comment]
> Sorry for using the wrong link, we've updated and fixed it, thanks for pointing out our mistake!

Hi @YangBin55 ,

Thank you for the quick update!

I just downloaded the files, and everything works perfectly now.

Just a quick note: the link to the pseudo-labels in the `Self-Training and Data-Efficient` section still seems to need updating.

https://github.com/SooLab/Part2Object/blob/65d728edecdb461bf6fd88c173996874ae862c45/README.md?plain=1#L79-L83

**Comment by LydJason** [comment]
I think the problem of the link to the pseudo-labels still exists.
Could you please update the links to point to the correct files? Thanks again for your hard work and support!
