### ISSUE TITLE
Issue about train_database.yaml

### ISSUE THREAD

**Issue by liuxuexun** [SooLab/Part2Object#8]
Hi, thank you for opening your great work. 

When I run `sh scripts/scannet/scannet_val.sh`, the code exit by reporting `generate data/processed/scannet/train_database.yaml first`.

I want to know how can I generate this file?

Thank you very much!

**Comment by zhangyl4** [comment]
We use [Mask3D](https://github.com/JonasSchult/Mask3D) codebase and follow it to process data for train and evaluate.  This file will be generated after you run Mask3D data preprocess.
